/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '2/03/16 8:35' with Gradle 2.6
 *
 * @author mati, @date 2/03/16 8:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
